CREATE SCHEMA IF NOT EXISTS ot_xm_film_ticket;

CREATE TABLE IF NOT EXISTS ot_xm_film_ticket.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (role, username)
);

CREATE TABLE IF NOT EXISTS ot_xm_film_ticket.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  status TEXT,
  owner TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT,
  extra JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO ot_xm_film_ticket.accounts (id, role, username, password, display_name) VALUES
  (1, 'admin', 'admin', 'admin', '平台管理员'),
  (2, 'user', 'user', '123456', '观影用户'),
  (3, 'staff', 'cinema01', '123456', '影院运营')
ON CONFLICT (role, username) DO UPDATE SET
  password = EXCLUDED.password,
  display_name = EXCLUDED.display_name;

INSERT INTO ot_xm_film_ticket.items (id, module_key, title, subtitle, status, owner, amount, description, extra) VALUES
  (1, 'film', '影片管理演示记录1', '影片、类型、演员、上映状态和热度', '进行中', '平台管理员', 10, '电影票务管理平台的影片管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (2, 'film', '影片管理演示记录2', '影片、类型、演员、上映状态和热度', '待处理', '观影用户', 20, '电影票务管理平台的影片管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (3, 'film', '影片管理演示记录3', '影片、类型、演员、上映状态和热度', '已完成', '影院运营', 30, '电影票务管理平台的影片管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (4, 'cinema', '影院管理演示记录1', '影院、区域、影厅和放映能力', '进行中', '平台管理员', 10, '电影票务管理平台的影院管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (5, 'cinema', '影院管理演示记录2', '影院、区域、影厅和放映能力', '待处理', '观影用户', 20, '电影票务管理平台的影院管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (6, 'cinema', '影院管理演示记录3', '影院、区域、影厅和放映能力', '已完成', '影院运营', 30, '电影票务管理平台的影院管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (7, 'show', '场次排片演示记录1', '影片场次、价格、座位和时间', '进行中', '平台管理员', 10, '电影票务管理平台的场次排片模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (8, 'show', '场次排片演示记录2', '影片场次、价格、座位和时间', '待处理', '观影用户', 20, '电影票务管理平台的场次排片模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (9, 'show', '场次排片演示记录3', '影片场次、价格、座位和时间', '已完成', '影院运营', 30, '电影票务管理平台的场次排片模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (10, 'order', '票务订单演示记录1', '购票、支付、取票和退票状态', '进行中', '平台管理员', 10, '电影票务管理平台的票务订单模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (11, 'order', '票务订单演示记录2', '购票、支付、取票和退票状态', '待处理', '观影用户', 20, '电影票务管理平台的票务订单模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (12, 'order', '票务订单演示记录3', '购票、支付、取票和退票状态', '已完成', '影院运营', 30, '电影票务管理平台的票务订单模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (13, 'comment', '评论评分演示记录1', '观众评论、评分和收藏', '进行中', '平台管理员', 10, '电影票务管理平台的评论评分模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (14, 'comment', '评论评分演示记录2', '观众评论、评分和收藏', '待处理', '观影用户', 20, '电影票务管理平台的评论评分模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (15, 'comment', '评论评分演示记录3', '观众评论、评分和收藏', '已完成', '影院运营', 30, '电影票务管理平台的评论评分模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (16, 'notice', '公告视频演示记录1', '公告、宣传片和运营信息', '进行中', '平台管理员', 10, '电影票务管理平台的公告视频模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (17, 'notice', '公告视频演示记录2', '公告、宣传片和运营信息', '待处理', '观影用户', 20, '电影票务管理平台的公告视频模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (18, 'notice', '公告视频演示记录3', '公告、宣传片和运营信息', '已完成', '影院运营', 30, '电影票务管理平台的公告视频模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  module_key = EXCLUDED.module_key,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  status = EXCLUDED.status,
  owner = EXCLUDED.owner,
  amount = EXCLUDED.amount,
  description = EXCLUDED.description,
  extra = EXCLUDED.extra,
  updated_at = now();

SELECT setval(pg_get_serial_sequence('ot_xm_film_ticket.accounts', 'id'), COALESCE((SELECT MAX(id) FROM ot_xm_film_ticket.accounts), 1), true);
SELECT setval(pg_get_serial_sequence('ot_xm_film_ticket.items', 'id'), COALESCE((SELECT MAX(id) FROM ot_xm_film_ticket.items), 1), true);

CREATE OR REPLACE FUNCTION public.ot_xm_film_ticket_demo_rest(
  p_table_name TEXT,
  p_method TEXT DEFAULT 'GET',
  p_query JSONB DEFAULT '{}'::jsonb,
  p_payload JSONB DEFAULT '{}'::jsonb
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_schema CONSTANT TEXT := 'ot_xm_film_ticket';
  v_table TEXT;
  v_sql TEXT;
  v_rows JSONB := '[]'::jsonb;
  v_key TEXT;
  v_value TEXT;
  v_where TEXT := '';
  v_order TEXT := '';
  v_limit TEXT := '';
  v_set TEXT := '';
  v_columns TEXT := '';
  v_values TEXT := '';
BEGIN
  IF p_table_name NOT IN ('accounts', 'items') THEN
    RAISE EXCEPTION 'table is not allowed: %', p_table_name;
  END IF;

  v_table := format('%I.%I', v_schema, p_table_name);

  FOR v_key, v_value IN SELECT key, value #>> '{}' FROM jsonb_each(p_query)
  LOOP
    IF v_key = 'select' THEN
      CONTINUE;
    ELSIF v_key = 'order' THEN
      v_order := ' ORDER BY ' || quote_ident(split_part(v_value, '.', 1)) ||
        CASE WHEN lower(split_part(v_value, '.', 2)) = 'desc' THEN ' DESC' ELSE ' ASC' END;
    ELSIF v_key = 'limit' THEN
      v_limit := ' LIMIT ' || LEAST(GREATEST(v_value::int, 1), 200);
    ELSIF v_value LIKE 'eq.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' = ' || quote_literal(substring(v_value FROM 4));
    ELSIF v_value LIKE 'ilike.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' ILIKE ' || quote_literal(substring(v_value FROM 7));
    END IF;
  END LOOP;

  IF upper(p_method) = 'GET' THEN
    v_sql := 'SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM (SELECT * FROM ' || v_table || v_where || v_order || v_limit || ') t';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'POST' THEN
    SELECT string_agg(quote_ident(key), ', '), string_agg(quote_literal(value #>> '{}'), ', ')
      INTO v_columns, v_values
    FROM jsonb_each(p_payload)
    WHERE key <> 'id';
    IF v_columns IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'INSERT INTO ' || v_table || ' (' || v_columns || ') VALUES (' || v_values || ') RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'PATCH' THEN
    SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value #>> '{}'), ', ')
      INTO v_set
    FROM jsonb_each(p_payload)
    WHERE key <> 'id' AND key <> 'created_at';
    IF v_set IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'UPDATE ' || v_table || ' SET ' || v_set || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'DELETE' THEN
    v_sql := 'DELETE FROM ' || v_table || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  END IF;

  RAISE EXCEPTION 'method is not allowed: %', p_method;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ot_xm_film_ticket_demo_rest(TEXT, TEXT, JSONB, JSONB) TO anon, authenticated, service_role;
